# Foundry Configuration File
# Default definitions: https://github.com/gakonst/foundry/blob/b7917fa8491aedda4dd6db53fbb206ea233cd531/config/src/lib.rs#L782
# See more config options at: https://github.com/gakonst/foundry/tree/master/config

[profile.default]
solc_version = '0.8.19'
auto_detect_solc = false
optimizer = true
optimizer_runs = 1_000
build_info = true
extra_output = ["storageLayout"]
libs = ["node_modules", "lib"]
fs_permissions = [{ access = "read", path = "./"}]

[fmt]
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
libs = ["node_modules", "lib"]

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_MAINNET_API_KEY}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_SEPOLIA_API_KEY}"
polygon = "https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_POLYGON_API_KEY}"
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_ARBITRUM_API_KEY}"
optimism = "https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_MAINNET_API_KEY}"
base = "https://radial-alien-bush.base-mainnet.quiknode.pro/${QUICKNODE_BASE_API_KEY}/"

[etherscan]
mainnet = { key = "${MAIN_ETHERSCAN_API_KEY}" }
sepolia = { key = "${MAIN_ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
arbitrum = { key = "${ARBISCAN_API_KEY}" }
optimism = { key = "${OPT_ETHERSCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }

