name: Slither Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: "recursive"

    - name: "Install Foundry"
      uses: "foundry-rs/foundry-toolchain@v1"

    - name: "Build the Solidity code"
      run: "forge build"

    - name: Run Slither
      uses: crytic/slither-action@v0.3.0
      id: slither
      with:
        node-version: 16
        sarif: results.sarif
        fail-on: none
        slither-args: --filter-paths "lib/prb-math"

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.slither.outputs.sarif }}