name: Solhint Check

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    solhint:
        name: Run Solhint
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Set Up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x

            - id: yarn-cache
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - uses: actions/cache@v1
              with:
                  path: ${{ steps.yarn-cache.outputs.dir }}
                  key: yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      yarn-

            - run: yarn
            - name: Run Solhint
              run: yarn solhint '**/*.sol'
